services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    container_name: graphql_api
    restart: unless-stopped
    image: graphql_api:latest
    volumes:
      - ./app.py:/app/app.py:Z
      - ./server:/app/server:Z
      - ./manage.py:/app/manage.py:Z
    ports:
      - '$PORT:$PORT'
    env_file:
      - .env
    environment:
      - WATCHFILES_FORCE_POLLING=true
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
    depends_on:
      - mongo
      - redis
    command: >
      sh -c "python manage.py migrate && python manage.py seed-all && uvicorn app:app --host 0.0.0.0 --port $PORT --reload --ws websockets --proxy-headers --timeout-graceful-shutdown 2"

  mongo:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

volumes:
  mongo_data:
